version: '3.7'
services:
  web:
    image: sunnywalden/service-statics:latest
    container_name: service_static
    ports:
      - "8000:8000"
    environment:
      ENV_TYPE: prod
      EXTERNAL: false
    volumes:
      - /data/service_static/configs/:/opt/service_static/configs/
    networks:
      - service_static
    restart: always

networks:
  service_static:
    driver: bridge