{
 "title": "SOP-SERVICE",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": "sop-api" },
   {
    "name": "env",
    "label": "environment",
    "query": "label_values(jvm_memory_used_bytes{job=~\"$job\"},env)"
   },
   { "name": "product", "query": "PLATFORM" },
   {
    "name": "production",
    "label": "产品",
    "query": "label_values(service_health_status,product)"
   },
   {
    "name": "environment",
    "label": "环境类型",
    "query": "label_values(service_health_status{product=~\"$production|.*\"},env_type)"
   },
   {
    "name": "service",
    "label": "服务",
    "query": "label_values(service_health_status{env_type=~\"$environment|.*\",product=~\"$production|sop\"},service)"
   },
   {
    "name": "host",
    "label": "主机",
    "query": "label_values(service_health_status{env_type=~\"$environment\",product=~\"$production|sop\",service=~\"$service\"},hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "$service服务状态",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "repeat": "service",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(service_health_status{env_type=~\"$environment\",product=~\"$production\",hostname=~\"$host|.*\",service=~\"$service\"}) * 100"
    }
   ]
  },
  {
   "title": "$service服务可用性",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(avg_over_time(service_health_status{env_type=~\"$environment\",product=~\"$production\",hostname=~\"$host|.*\",service=~\"$service\"}[24h])) * 100"
    }
   ]
  },
  {
   "title": "SOP",
   "type": "table",
   "gridPos": { "h": 32, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "count(process_uptime_seconds{service=~\"PLATFORM-.*\",env=~\"$env\"}) by(application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "$service服务状态",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 5 },
   "repeat": "service",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(service_health_status{env_type=~\"$environment\",product=~\"$production\",hostname=~\"$host|.*\",service=~\"$service\"}) * 100",
     "legendFormat": "$service"
    }
   ]
  },
  {
   "title": "SOP",
   "type": "table",
   "gridPos": { "h": 18, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(process_uptime_seconds{service=~\"$product.*\",env=~\"$env\"}) by(application)",
     "legendFormat": "{{application}}"
    }
   ]
  }
 ]
}